---
- name: Ensure Gluster brick and mount directories exist.
  file: "path={{ item }} state=directory mode=0777"  # danger zone, but okay for throwaway deployments
  with_items:
  - "{{ gluster_brick_dir }}"
  - "{{ gluster_mount_dir }}"

- name: Configure Gluster volume.
  gluster_volume:
    state: present
    force: yes
    name: "{{ gluster_brick_name }}"
    brick: "{{ gluster_brick_dir }}"
    #replicas: 3
    cluster: "{{ groups.cluster | join(',') }}"
    host: "{{ ansible_hostname }}"
  run_once: true

- name: Ensure Gluster volume is mounted.
  mount:
    name: "{{ gluster_mount_dir }}"
    src: "{{ ansible_hostname }}:/{{ gluster_brick_name }}"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted
...